# Generated by Django 4.2.2 on 2023-07-03 19:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='blogmolde',
            options={'verbose_name': 'وبلاگ', 'verbose_name_plural': 'وبلاگ ها'},
        ),
        migrations.AddField(
            model_name='blogmolde',
            name='title',
            field=models.CharField(default=2, max_length=1000, verbose_name='تایتل'),
            preserve_default=False,
        ),
    ]
