# Generated by Django 4.2.2 on 2023-07-03 09:30

import ckeditor.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='gameMode',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=400, verbose_name='اسم بازی')),
            ],
            options={
                'verbose_name': 'دسته بندی ',
                'verbose_name_plural': 'دسته بندی ها',
            },
        ),
        migrations.CreateModel(
            name='lDitaile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=300, verbose_name='تایتل')),
                ('body', ckeditor.fields.RichTextField(verbose_name='توصیحات')),
                ('img1', models.URLField(verbose_name='عکس یک')),
                ('img2', models.URLField(verbose_name='عکس دو')),
                ('img3', models.URLField(verbose_name='عکس سه')),
                ('film', models.URLField(verbose_name='فیلم')),
            ],
            options={
                'verbose_name': 'بازی ',
                'verbose_name_plural': 'بازی ها ',
            },
        ),
    ]
