# Generated by Django 4.2.2 on 2023-07-03 09:32

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='lditaile',
            name='category',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='home.gamemode', verbose_name='دسته بندی'),
            preserve_default=False,
        ),
    ]
