# Generated by Django 4.2.2 on 2023-07-03 09:45

import ckeditor.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0002_lditaile_category'),
    ]

    operations = [
        migrations.AlterField(
            model_name='lditaile',
            name='body',
            field=ckeditor.fields.RichTextField(blank=True, null=True, verbose_name='توصیحات'),
        ),
        migrations.AlterField(
            model_name='lditaile',
            name='film',
            field=models.URLField(blank=True, null=True, verbose_name='فیلم'),
        ),
        migrations.AlterField(
            model_name='lditaile',
            name='img1',
            field=models.URLField(blank=True, null=True, verbose_name='عکس یک'),
        ),
        migrations.AlterField(
            model_name='lditaile',
            name='img2',
            field=models.URLField(blank=True, null=True, verbose_name='عکس دو'),
        ),
        migrations.AlterField(
            model_name='lditaile',
            name='img3',
            field=models.URLField(blank=True, null=True, verbose_name='عکس سه'),
        ),
    ]
