# Generated by Django 4.2.2 on 2023-07-03 10:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0003_alter_lditaile_body_alter_lditaile_film_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='lditaile',
            name='Money',
            field=models.IntegerField(default=0, verbose_name='قیمت'),
        ),
    ]
