# Generated by Django 4.2.2 on 2023-07-03 10:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0004_lditaile_money'),
    ]

    operations = [
        migrations.AddField(
            model_name='lditaile',
            name='slug',
            field=models.CharField(default=2, max_length=1000, verbose_name='لینک'),
            preserve_default=False,
        ),
    ]
