# Generated by Django 4.2.2 on 2023-07-03 10:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0007_alter_lditaile_link'),
    ]

    operations = [
        migrations.AddField(
            model_name='lditaile',
            name='alt',
            field=models.CharField(blank=True, max_length=300, null=True, verbose_name='توضیحات عکس'),
        ),
    ]
