# Generated by Django 4.2.2 on 2023-07-03 10:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0008_lditaile_alt'),
    ]

    operations = [
        migrations.AddField(
            model_name='lditaile',
            name='like',
            field=models.IntegerField(default=0, verbose_name='تعداد لایک'),
        ),
    ]
