# Generated by Django 4.2.2 on 2023-07-04 12:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0010_gamemode_img_gamemode_my_id'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='lditaile',
            name='link',
        ),
        migrations.AddField(
            model_name='lditaile',
            name='slug',
            field=models.SlugField(default=1, verbose_name='لینک'),
            preserve_default=False,
        ),
    ]
